syntax = "proto3";

message Empty {}

message TestingDaughterboard {}

message DiodeDaughterboard {}

message BasicDaughterboard {}

message DaughterboardInfo {
    fixed64 unique_id = 1;

    // These will be < 32 bits, protobuf uses varint encoding.
    uint32 firm_version_major = 2; // 16 bit
    uint32 firm_version_minor = 3; // 8 bit
    uint32 firm_version_patch = 4; // 8 bit
    
    oneof info {
        // type-specific info
        TestingDaughterboard test_daughter = 5;
        BasicDaughterboard basic_daughter = 6;
        DiodeDaughterboard diode_daughter = 7;
    }
}

message MotherboardTopology {
    message NullableDaughterboardInfo {
        oneof daughterboard {
            Empty empty = 1;
            DaughterboardInfo daughterboard_info = 2;
        }
    }

    fixed64 unique_id = 1;

    uint32 hardware_revision = 2; // 16 bit

    uint32 firm_version_major = 3; // 16 bit
    uint32  firm_version_minor = 4; // 8 bit
    uint32  firm_version_patch = 5; // 8 bit
    
    repeated NullableDaughterboardInfo daughterboards = 6;
}

message TopologyRequest {}

message TopologyResponse {
    repeated MotherboardTopology motherboards = 1;
}

// ----------
//  Commands
// ----------

message ProgramXbar {
    uint32 crossbar_id = 1;
    uint32 row = 2;
    uint32 column = 3;
}

message ProgrammingPayload {
    oneof data {
        ProgramXbar xbar = 1;
    }
}

message ProgrammingCommand {
    // address
    uint32 motherboard_id = 1; // 8 bit
    uint32 daughterboard_id = 2; // 8 bit

    ProgrammingPayload payload = 3;
}

message StopProgramming {
}

message StopProgrammingResponse {
    uint32 complete_count = 1;
}

// A command a daughterboard will receive from its mother
message DaughterCommand {
    oneof cmd {
        TopologyRequest topo = 1;
        ProgrammingPayload prog = 2;
        StopProgramming stop = 3;
    }
}

// A response a daughterboard will send to its mother
message DaughterResponse {
    oneof data {
        DaughterboardInfo info = 1;
        StopProgrammingResponse stop = 2;
    }
}

// A command a motherboard will receive from host/grandmother
message MotherCommand {
    oneof cmd {
        TopologyRequest topology_request = 1;  
        ProgrammingCommand dummy_command = 2;
        StopProgramming stop = 3;
    }
}

// A response a motherboard will send to host/grandmother
message MotherResponse {
    oneof data {
        MotherboardTopology info = 1;
        StopProgrammingResponse stop = 2;
    }
}
