syntax="proto3";

// Dummy protobuf for testing

// Google's protoc cannot accept the "(nanopb)" annotations by default, so we
// preprocess the file with a simple sed script. Anything between a
// "/*ifnpb*/" and "/*endif*/" will be removed if compiling with protoc
// These annotations must be on the same line to make sed happy

message Command1 {
  int32 field1 = 1;
  uint64 field2 = 2;
}

message Command2 {
  string cmd_name = 1 /*ifnpb*/ [ (nanopb).max_length = 31 ] /*endif*/ ; 
}

message Command {
  oneof cmd {
    Command1 cmd1 = 1;
    Command2 cmd2 = 2;
  }
};
