; --------------------------
; --    BOARD CONFIGS     --
; --------------------------

; Motherboard config
[env:motherboard]
extends = rp2350
build_src_filter = -<*> +<motherboard/*>
build_src_flags = -Wall -Wextra -Werror -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wnull-dereference -Wshadow -Wvla -Wswitch-enum -Winvalid-pch -Wstack-usage=1024
lib_deps = https://github.com/nanopb/nanopb.git
custom_nanopb_project_dir = $PROJECT_DIR/../proto/
custom_nanopb_protos = +<*.proto>

; General Daughterboard Config 
; Extended by Specific daughter boards
[daughterboard]

; Legacy Config
; Original IRLTSPICE Board from Senior Design
[env:legacy]
extends = stm32f0
build_src_filter = -<*> +<legacy/*>
build_flags = ${stm32f0.build_flags} -Iinclude/legacy
build_src_flags = ${stm32f0.build_src_flags} -O0
upload_command = openocd -f openocd.cfg -c "program .pio/build/legacy/firmware.elf verify reset exit"

; -------------------------------
; --     PLATFORM CONFIGS      --
; -------------------------------

; STM Configs
; Used in legacy design and could be useful for daughterboards
[stm32f0]
platform = ststm32
board = nucleo_f091rc
framework = stm32cube
build_flags = -D STM32F091xc
debug_server = 
    ${platformio.packages_dir}/tool-openocd/bin/openocd
    -f
    openocd.cfg
build_src_flags = -DSTM32F091
upload_protocol = stlink
debug_init_break = tbreak main
board_build.f_cpu = 48000000L
monitor_speed = 115200
monitor_eol = LF

; RP Configs
[rp2350]
platform = https://github.com/norandomtechie/platform-raspberrypi#feature/proton-picosdk-support
board = proton
framework = picosdk
debug_tool = picoprobe
upload_protocol = picoprobe
monitor_speed = 115200
